name: fireside
description: "Fireside - self-hosted Discord alternative for small communities."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_webrtc: ^0.12.5
  flutter_riverpod: ^2.5.1
  riverpod: ^2.5.1
  go_router: ^14.2.0
  web_socket_channel: ^3.0.0
  dio: ^5.4.3
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.3.0
  flutter_markdown: ^0.7.3
  cached_network_image: ^3.3.1
  file_picker: ^8.0.0+1
  just_audio: ^0.9.40
  flutter_local_notifications: ^17.2.2
  google_fonts: ^6.2.1
  intl: ^0.19.0
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/icons/

  fonts:
    - family: GeistMono
      fonts:
        - asset: assets/fonts/GeistMono-Regular.ttf
        - asset: assets/fonts/GeistMono-Bold.ttf
          weight: 700
    - family: IBMPlexMono
      fonts:
        - asset: assets/fonts/IBMPlexMono-Regular.ttf
        - asset: assets/fonts/IBMPlexMono-Bold.ttf
          weight: 700
